services:
  client:
    image: xprss/recipe-scaler:${VERSION:-latest}
    container_name: recipe-scaler
    restart: unless-stopped
    ports:
      - "9000:9000"

networks:
  vividinet:
    driver: bridge
